# Generated by Django 5.2.17 on 2026-09-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_replace_generic_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_source_url',
            field=models.URLField(blank=True),
        ),
    ]
